import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Farmer Ju</a>
        </h1>
        <div>
          <iframe src="https://embeds.beehiiv.com/8b402f1e-813b-4b72-a132-4ca3fd1b56d5?slim=true" data-test-id="beehiiv-embed" frameborder="0" scrolling="no" style= {{margin: 0, borderRadius: '0px !important', backgroundColor: 'transparent'}} ></iframe>
        </div>

        

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://farmerju.beehiiv.com/p/case-vertical-farms" className={styles.card}>
            <h2>The Case for Vertical Farms &rarr;</h2>
            <p>Learn how Vertical Farms can grow fresh food, locally... fast.</p>
          </a>

          <a href="https://farmerju.beehiiv.com/p/mutant-foods" className={styles.card}>
            <h2>Mutant Foods !!! &rarr;</h2>
            <p>What are GMOs, and are they as bad as everyone makes them out to be?</p>
          </a>

          <a
            href="https://farmerju.beehiiv.com/p/self-driving-tractor-takeover"
            className={styles.card}
          >
            <h2>Self Driving Tractors &rarr;</h2>
            <p>Self driving cars have already taken over... they just work in fields</p>
          </a>

          <a
            href="https://farmerju.beehiiv.com/p/silvopasture-august-21"
            className={styles.card}
          >
            <h2>Silvopasture &rarr;</h2>
            <p>
              Cows in forests? Farmers selling carbon credits... the new business of Silvopasture
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
